

export const templates = [
  {
    name: "BookShelf",
    description: "Votre bibliothèque numérique Des e-books de qualité, accessibles instantanément. Lecture simplifiée, contenu exceptionnel.",
    tags: ["NextJs", "Tailwind CSS", "Lucide React"],
    image: "/images/1.png",
    category:"E-commerce",
    popular: true,
    slug: "saas-starter",
    demoUrl: "https://bookshelf-seven-sooty.vercel.app/",
  },
  {
    name: "Stratégie Réseaux Sociaux",
    description: "Campagne complète de gestion et création de contenu pour une marque de luxe, augmentant l'engagement de 300%.",
    tags: ["Social Media", "Content","Analytics"],
    category: "Marketing Digital",
    image: "/images/2.jpg",
    popular: false,
    slug: "ecommerce",
    demoUrl: "https://netero.dev/demo/ecommerce",
  },
  {
    name: "SynergERP",
    description: "Système de gestion intégré pour une PME avec automatisation des processus clés et reporting en temps réel.",
    tags: ["ERP", "Automation", "Dashboard"],
    category: "Automatisation",
    image: "/images/3.jpg",
    popular: false,
    slug: "blog",
    demoUrl: "https://netero.dev/demo/blog",
  },
  {
    name: "Application Mobile",
    description: "Application mobile native pour la gestion de services à domicile avec géolocalisation et paiement intégré.",
    tags: ["React Native", "Mobile","GPS"],
    category: "Développement", 
    image: "/images/4.jpg",
    popular: false,
    slug: "admin-dashboard",
    demoUrl: "https://netero.dev/demo/admin-dashboard",
  },
  {
    name: "GlobalSolution & Services",
    description: "Site web moderne et responsive pour une entreprise de logistique et transport avec animations fluides et design.",
    tags: ["Next.js", "Responsive","Animation"],
    category: "Web Design",
    image: "/images/5.png",
    popular: false,
    slug: "portfolio",
    demoUrl: "https://netero.dev/demo/portfolio",
  },
  {
    name: "Lukia",
    description: "Chatbot intelligent pour le service client avec traitement du langage naturel et intégration CRM.",
    tags: ["AI", "NLP","Chatbot"],
    category: "IA",
    image: "/images/6.png",
    popular: true,
    slug: "landing-startup",
    demoUrl: "https://netero.dev/demo/landing-startup",
  },
  {
    name: "Marketplace B2B",
    description: "Plateforme de mise en relation entre fournisseurs et acheteurs avec système de notation et paiement sécurisé.",
    tags: ["Marketplace", "B2B","Payment"],
    image: "/images/7.jpg",
    category:"E-commerce",
    popular: false,
    slug: "restaurant",
    demoUrl: "https://netero.dev/demo/restaurant",
  },
  {
    name: "Campagne SEO",
    description: "Optimisation complète du référencement naturel pour un site e-commerce, augmentant le trafic de 250%..",
    tags: ["SEO", "Analytics","Content"],
    category: "Marketing Digital",
    image: "/images/8.jpg",
    popular: false,
    slug: "elearning",
    demoUrl: "https://netero.dev/demo/elearning",
  },
  {
    name: "Système CRM",
    description: "Solution CRM personnalisée pour la gestion de la relation client avec automatisation des ventes.",
    tags: ["CRM", "Sales","Automation"],
    category: "Automatisation",
    image: "/images/9.jpg",
    popular: false,
    slug: "agency",
    demoUrl: "https://netero.dev/demo/agency",
  },
];
